kubernetesClusterDomain: cluster.local
kubernetesNamespace: aisquared
aisquaredConfig:
  allowedHost: ""
  allowedSourceIP: "0.0.0.0/0"
  apiHost: api.squared.ai
  appRevision: unknown
  appEnv: community
  appsignalPushApiKey: yourkey
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  azureSpot: false
  databricksDriverPath: /opt/simba/spark/lib/64/libsparkodbc_sb64.so
  dbHost: aisquared-postgresql
  dbPassword: password
  dbPort: "5432"
  dbUsername: aisquared
  grpcEnableForkSupport: 1
  jwtSecret: ""
  newRelicKey: yourkey
  nginxProxyBodySize: 2m
  privateRepo: false
  railsEnv: development
  railsLogLevel: info
  registrySecretName: mwregistrysecret
  secretKeyBase: ""
  skipDbMigration: "false"
  smtpAddress: smtp.yourdomain.com
  smtpBrandName: "AI Squared"
  smtpHost: yourdomain.com
  smtpPassword: yourpassword
  smtpPort: "587"
  smtpUsername: yourusername
  smtpSenderEmail: admin@yourdomain.com
  solidWorkerHost: solid.squared.ai
  snowflakeDriverPath: /usr/lib/snowflake/odbc/lib/libSnowflake.so
  storageAccessKey: "myaccesskey"
  storageAccountName: ""
  syncExtractorBatchSize: "1000"
  syncExtractorThreadPoolSize: "10"
  syncLoaderBatchSize: "1000"
  syncLoaderThreadPoolSize: "10"
  temporalActivityThreadPoolSize: "20"
  temporalClientChain: /certs/temporal.chain.pem
  temporalClientKey: /certs/temporal.pem
  temporalHost: aisquared-temporal
  temporalNamespace: aisquared-dev
  temporalPort: "7233"
  temporalPostgresDefaultPort: "5432"
  temporalPostgresPassword: password
  temporalPostgresSsl: false
  temporalPostgresUser: aisquared
  temporalPostgresqlVersion: "13"
  temporalRootCert: /certs/temporal.key
  temporalTaskQueue: sync-dev
  temporalUiHost: temporal.squared.ai
  temporalUiVersion: 2.23.2
  temporalVersion: 1.22.4
  temporalWorkflowThreadPoolSize: "10"
  tlsAdminEmail: admin@squared.ai
  tlsCertIssuer: letsencrypt-staging
  uiHost: app.squared.ai
  userEmailVerification: "false"
  viteApiHost: api.squared.ai
  viteAppsignalPushApiKey: yourkey
  viteBrandName: "AI Squared"
  viteLogoUrl: ""
  viteBrandColor: ""
  viteBrandHoverColor: ""
  viteFavIconUrl: ""
  workerHost: worker.squared.ai

automountServiceAccountToken:
  enabled: true

externalDNS:
  enabled: false

nginxIngress:
  enabled: true
  enableMetrics: false

kongIngress:
  enabled: false
  plugins:
    prometheus:
      enabled: false

awsIngress:
  enabled: false
  acmCertificateArn: ""
  albScheme: internet-facing
  sslPolicy: ELBSecurityPolicy-2016-08

serviceAccount:
  create: false
  name: aisquared-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/example-role

secretsStore:
  enabled: false
  mwSecretAlias: mw-f01dd256e712
  temporalSecretAlias: temporal-f01dd256e712
  temporalVisibilitySecretAlias: temporal-visibility-f01dd256e712
  tempStoreSecretAlias: temp-store-f01dd256e712

  tempStoreSecretEnabled: false
  temporalSecretEnabled: false

  MWCredsSecretName: ""
  TemporalCredsSecretName: ""
  TemporalVisibilityCredsSecretName: ""
  TempStoreCredsSecretName: ""

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  capabilities:
    drop:
      permissions:
        - "ALL"

globalImagePullPolicy: IfNotPresent

multipleDbHosts:
  enabled: false

  aisquaredDBHost: ""
  aisquaredDBName: ""

  temporalDbName: ""
  temporalDbHost: ""
  temporalDbUsername: ""
  temporalDbPassword: ""

  temporalVisibilityDbName: ""
  temporalVisibilityDbHost: ""
  temporalVisibilityDbUsername: ""
  temporalVisibilityDbPassword: ""

hpa:
  enabled: true
  aisquaredUI:
    minReplicas: 1
    maxReplicas: 10
    cpuAverageUtilizationPercentageThreshold: 80
    memoryAverageUtilizationPercentageThreshold: 75
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max
      scaleUp:
        stabilizationWindowSeconds: 45
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max
  aisquaredServer:
    minReplicas: 1
    maxReplicas: 10
    cpuAverageUtilizationPercentageThreshold: 80
    memoryAverageUtilizationPercentageThreshold: 60
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max
      scaleUp:
        stabilizationWindowSeconds: 45
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max
  aisquaredSolidWorker:
    minReplicas: 1
    maxReplicas: 10
    cpuAverageUtilizationPercentageThreshold: 80
    memoryAverageUtilizationPercentageThreshold: 50
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max
      scaleUp:
        stabilizationWindowSeconds: 45
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max
  aisquaredWorker:
    minReplicas: 1
    maxReplicas: 10
    cpuAverageUtilizationPercentageThreshold: 80
    memoryAverageUtilizationPercentageThreshold: 50
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max
      scaleUp:
        stabilizationWindowSeconds: 45
        policies:
          percentPolicy:
            type: Percent
            value: 100
            periodSeconds: 15
          podPolicy:
            type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max

aisquaredPostgresql:
  enabled: true
  annotations: {}
  aisquaredPostgresql:
    image:
      repository: postgres
      tag: "13"
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  replicas: 1
  type: ClusterIP
aisquaredServer:
  annotations: {}
  podSecurityContext:
    fsGroup: 1000
  aisquaredServer:
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    image:
      repository: aisquared/aisquared-server
      tag: latest
    resources:
      limits:
        cpu: "2"
        memory: "3Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  replicas: 1
  type: ClusterIP
aisquaredUI:
  annotations: {}
  podSecurityContext:
    fsGroup: 1000
  aisquaredUI:
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    image:
      repository: aisquared/aisquared-ui
      tag: latest
    resources:
      limits:
        cpu: "200m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  replicas: 1
  type: ClusterIP
aisquaredSolidWorker:
  annotations: {}
  healthPort: 9999
  podSecurityContext:
    fsGroup: 1000
  aisquaredSolidWorker:
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    args:
      - sh
      - -c
      - |
        ./app/solid_queue/cli/worker
    image:
      repository: aisquared/aisquared-server
      tag: latest
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 1Gi
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  replicas: 1
  type: ClusterIP
aisquaredWorker:
  annotations: {}
  healthPort: 4567
  podSecurityContext:
    fsGroup: 1000
  aisquaredWorker:
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    args:
      - sh
      - -c
      - |
        ./app/temporal/cli/register_namespace && ./app/temporal/cli/worker
    image:
      repository: aisquared/aisquared-server
      tag: latest
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 1Gi
  ports:
    - name: "4567"
      port: 4567
      targetPort: 4567
  replicas: 1
  type: ClusterIP
pvc:
  pvc:
    storageRequest: 100Mi
    storageClassName: "default"
temporal:
  enabled: true
  annotations: {}
  podSecurityContext:
    fsGroup: 1000
  ports:
    - name: "7233"
      port: 7233
      targetPort: 7233
  replicas: 1
  temporal:
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    env:
      db: postgresql
    image:
      repository: temporalio/auto-setup
      tag: 1.22.4
    initContainer:
      image:
        repository: temporalio/auto-setup
        tag: 1.22.4
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  type: ClusterIP
temporalUi:
  annotations: {}
  podSecurityContext:
    fsGroup: 5000
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  replicas: 1
  temporalUi:
    containerSecurityContext:
      runAsUser: 5000
      runAsGroup: 5000
    env:
      temporalAddress: aisquared-temporal:7233
      temporalCorsOrigins: http://localhost:3000
      temporalUiPort: "8080"
    image:
      repository: temporalio/ui
      tag: 2.22.3
    initContainer:
      image:
        repository: temporalio/ui
        tag: 2.22.3
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  type: ClusterIP
