apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-acme-challenge-service
  namespace: {{ .Values.kubernetesNamespace }}
spec:
  selector:
    app: {{ include "chart.fullname" . }}-acme-challenge
  ports:
    - protocol: TCP
      port: {{ (index .Values.acmeChallenge.ports 0).port }}
      targetPort: {{ (index .Values.acmeChallenge.ports 0).port }}
