{{- if .Values.box.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-box
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.box.type }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.box.ports | nindent 4 }}
{{- end }}