{{- if .Values.box.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-box-controller
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- end }}
