{{ if .Values.secretsStore.sandboxSecretEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "chart.fullname" . }}-secret-provider-class-sandbox
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    app: {{ include "chart.fullname" . }}-secret-provider-class-sandbox
    io.kompose.service: {{ include "chart.fullname" . }}-secret-provider-class-sandbox
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ required "SandboxCredsSecretName is required" .Values.secretsStore.SandboxCredsSecretName }}
        objectType: secretsmanager
        jmesPath:
          - path: agenticCodingBuildToken
            objectAlias: AGENTIC_CODING_BUILD_TOKEN
          - path: codingAgentModelApiKey
            objectAlias: CODING_AGENT_MODEL_API_KEY
          - path: modalTokenId
            objectAlias: MODAL_TOKEN_ID
          - path: modalTokenSecret
            objectAlias: MODAL_TOKEN_SECRET
          - path: dockerHubRegistryUsername
            objectAlias: DOCKER_HUB_REGISTRY_USERNAME
          - path: dockerHubRegistryPassword
            objectAlias: DOCKER_HUB_REGISTRY_PASSWORD
  secretObjects:
  - secretName: {{ .Values.secretsStore.sandboxSecretAlias }}
    type: Opaque
    data:
      - objectName: AGENTIC_CODING_BUILD_TOKEN
        key: AGENTIC_CODING_BUILD_TOKEN
      - objectName: CODING_AGENT_MODEL_API_KEY
        key: CODING_AGENT_MODEL_API_KEY
      - objectName: MODAL_TOKEN_ID
        key: MODAL_TOKEN_ID
      - objectName: MODAL_TOKEN_SECRET
        key: MODAL_TOKEN_SECRET
      - objectName: DOCKER_HUB_REGISTRY_USERNAME
        key: DOCKER_HUB_REGISTRY_USERNAME
      - objectName: DOCKER_HUB_REGISTRY_PASSWORD
        key: DOCKER_HUB_REGISTRY_PASSWORD
{{ end }}
