apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multiwoven-server-ingress
  namespace: {{ .Values.kubernetesNamespace }}

  labels:
  # {{- include "chart.labels" . | nindent 4 }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: app.squared.ai
  - http:
      paths:
      - backend:
          service:
            name: 'multiwoven-server'
            port:
              number: 3000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: 'multiwoven-ui'
            port:
              number: 8000
        path: /
        pathType: Prefix
    # host:  {{ .Values.multiwovenConfig.apiHost }}