apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    io.kompose.service: {{ include "chart.fullname" . }}-config
  {{- include "chart.labels" . | nindent 4 }}
data:
  ACTIVE_STORAGE_SERVICE: {{ .Values.multiwovenConfig.activeStorageService | quote }}
  ALLOWED_HOST: {{ .Values.multiwovenConfig.allowedHost | quote }}
  API_HOST: {{ .Values.multiwovenConfig.apiHost | quote }}
  APP_ENV: {{ .Values.multiwovenConfig.appEnv | quote }}
  APP_REVISION: {{ .Values.multiwovenConfig.appRevision | quote }}
  APPSIGNAL_APP_ENV: {{ .Values.multiwovenConfig.appEnv | quote }}
  APPSIGNAL_PUSH_API_KEY: {{ .Values.multiwovenConfig.appsignalPushApiKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.multiwovenConfig.awsAccessKeyId | quote }}
  AWS_REGION: {{ .Values.multiwovenConfig.awsRegion | quote }}
  AWS_S3_BUCKET: {{ .Values.multiwovenConfig.awsS3Bucket | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.multiwovenConfig.awsSecretAccessKey | quote }}
  BRAND_NAME: {{ .Values.multiwovenConfig.smtpBrandName | quote }}
  DATABRICKS_DRIVER_PATH: {{ .Values.multiwovenConfig.databricksDriverPath | quote }}
  DB_NAME: {{ .Values.multiwovenConfig.dbName | quote }}
  DB_PORT: {{ .Values.multiwovenConfig.dbPort | quote }}
  DB_HOST: {{ .Values.multiwovenConfig.dbHost | quote }}
  {{ if not .Values.secretsStore.enabled }}
  DB_PASSWORD: {{ .Values.multiwovenConfig.dbPassword | quote }}
  DB_USERNAME: {{ .Values.multiwovenConfig.dbUsername | quote }}
  {{ end }}
  GRPC_ENABLE_FORK_SUPPORT: {{ .Values.multiwovenConfig.grpcEnableForkSupport | quote }}
  HUBSPOT_API_KEY: {{ .Values.multiwovenConfig.hubspotApiKey | quote }}
  JWT_SECRET: {{ .Values.multiwovenConfig.jwtSecret | quote }}
  LEAD_CAPTURE_ENABLED: {{ .Values.multiwovenConfig.leadCaptureEnabled | quote }}
  NEW_RELIC_KEY: {{ .Values.multiwovenConfig.newRelicKey | quote }}
  RAILS_ENV: {{ .Values.multiwovenConfig.railsEnv | quote }}
  RAILS_LOG_LEVEL: {{ .Values.multiwovenConfig.railsLogLevel | quote }}
  SECRET_KEY_BASE: {{ .Values.multiwovenConfig.secretKeyBase | quote }}
  SKIP_DB_MIGRATION: {{ .Values.multiwovenConfig.skipDbMigration | quote }}
  SLACK_SIGNUP_CHANNEL_EMAIL: {{ .Values.multiwovenConfig.slackSignupChannelEmail | quote }}
  {{ if not .Values.multiwovenConfig.userEmailVerification}}
  SMTP_ADDRESS: {{ .Values.multiwovenConfig.smtpAddress | quote }}
  SMTP_HOST: {{ .Values.multiwovenConfig.smtpHost | quote }}
  SMTP_PASSWORD: {{ .Values.multiwovenConfig.smtpPassword | quote }}
  SMTP_PORT: {{ .Values.multiwovenConfig.smtpPort | quote }}
  SMTP_USERNAME: {{ .Values.multiwovenConfig.smtpUsername | quote }}
  SMTP_SENDER_EMAIL: {{ .Values.multiwovenConfig.smtpSenderEmail | quote }}
  {{ end }}
  SNOWFLAKE_DRIVER_PATH: {{ .Values.multiwovenConfig.snowflakeDriverPath | quote }}
  STORAGE_ACCESS_KEY: {{ .Values.multiwovenConfig.storageAccessKey }}
  STORAGE_ACCOUNT_NAME: {{ .Values.multiwovenConfig.storageAccountName }}
  SYNC_EXTRACTOR_BATCH_SIZE: {{ .Values.multiwovenConfig.syncExtractorBatchSize | quote }}
  SYNC_EXTRACTOR_THREAD_POOL_SIZE: {{ .Values.multiwovenConfig.syncExtractorThreadPoolSize | quote }}
  SYNC_LOADER_BATCH_SIZE: {{ .Values.multiwovenConfig.syncLoaderBatchSize | quote }}
  SYNC_LOADER_THREAD_POOL_SIZE: {{ .Values.multiwovenConfig.syncLoaderThreadPoolSize | quote }}
  TEMPORAL_ACTIVITY_THREAD_POOL_SIZE: {{ .Values.multiwovenConfig.temporalActivityThreadPoolSize | quote }}
  TEMPORAL_CLIENT_CHAIN: {{ .Values.multiwovenConfig.temporalClientChain | quote }}
  TEMPORAL_CLIENT_KEY: {{ .Values.multiwovenConfig.temporalClientKey | quote }}
  TEMPORAL_HOST: {{ .Values.multiwovenConfig.temporalHost | quote }}
  TEMPORAL_NAMESPACE: {{ .Values.multiwovenConfig.temporalNamespace | quote }}
  TEMPORAL_PORT: {{ .Values.multiwovenConfig.temporalPort | quote }}
  TEMPORAL_POSTGRES_DEFAULT_PORT: {{ .Values.multiwovenConfig.temporalPostgresDefaultPort | quote }}
  {{ if not .Values.secretsStore.enabled }}
  TEMPORAL_POSTGRES_PASSWORD: {{ .Values.multiwovenConfig.temporalPostgresPassword | quote }}
  {{ end }}
  TEMPORAL_POSTGRES_USER: {{ .Values.multiwovenConfig.temporalPostgresUser | quote }}
  TEMPORAL_POSTGRESQL_VERSION: {{ .Values.multiwovenConfig.temporalPostgresqlVersion | quote }}
  TEMPORAL_ROOT_CERT: {{ .Values.multiwovenConfig.temporalRootCert | quote }}
  TEMPORAL_TASK_QUEUE: {{ .Values.multiwovenConfig.temporalTaskQueue | quote }}
  TEMPORAL_UI_VERSION: {{ .Values.multiwovenConfig.temporalUiVersion | quote }}
  TEMPORAL_VERSION: {{ .Values.multiwovenConfig.temporalVersion | quote }}
  TEMPORAL_WORKFLOW_THREAD_POOL_SIZE: {{ .Values.multiwovenConfig.temporalWorkflowThreadPoolSize | quote }}
  TRACK: {{ .Values.multiwovenConfig.track | quote }}
  UI_HOST: {{ .Values.multiwovenConfig.uiHost | quote }}
  USER_EMAIL_VERIFICATION: {{ .Values.multiwovenConfig.userEmailVerification | quote }}
  VITE_API_HOST: {{ .Values.multiwovenConfig.viteApiHost | quote }}
  VITE_APPSIGNAL_PUSH_API_KEY: {{ .Values.multiwovenConfig.viteAppsignalPushApiKey | quote }}
  VITE_BRAND_NAME: {{ .Values.multiwovenConfig.viteBrandName | quote }}
  VITE_LOGO_URL: {{ .Values.multiwovenConfig.viteLogoUrl | quote }}
  VITE_BRAND_COLOR: {{ .Values.multiwovenConfig.viteBrandColor | quote }}
  VITE_BRAND_HOVER_COLOR: {{ .Values.multiwovenConfig.viteBrandHoverColor | quote }}
  VITE_FAV_ICON_URL: {{ .Values.multiwovenConfig.viteFavIconUrl | quote }}
