apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  namespace: {{ .Values.kubernetesNamespace }}

  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: {{ .Values.multiwovenConfig.tlsCertIssuer }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.multiwovenConfig.uiHost }}
    - {{ .Values.multiwovenConfig.apiHost }}
  {{ if .Values.temporal.enabled }}
    - {{ .Values.multiwovenConfig.temporalUiHost }}
  {{ end }}
    secretName: mw-tls-cert
  rules:
  - host:  {{ .Values.multiwovenConfig.uiHost }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-ui'
            port:
              number: 8000
        path: /(.*)
        pathType: Prefix
  - host: {{ .Values.multiwovenConfig.apiHost }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-server'
            port:
              number: 3000
        path: /(.*)
        pathType: Prefix
{{ if .Values.temporal.enabled }}
  - host: {{ .Values.multiwovenConfig.temporalUiHost }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-temporal-ui'
            port:
              number: 8080
        path: /(.*)
        pathType: Prefix
{{ end }}
