{{ if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: {{ include "chart.fullname" . }}-secret-provider-class-mw
    namespace: {{ .Values.kubernetesNamespace }}
    labels:
      app: {{ include "chart.fullname" . }}-secret-provider-class-mw
      service: {{ include "chart.fullname" . }}-secret-provider-class-mw
      {{- include "chart.labels" . | nindent 4 }}
spec:
    provider: aws
    parameters:
        objects: |
          - objectName: {{ required "MWCredsSecretName is required" .Values.secretsStore.MWCredsSecretName }}
            objectType: secretsmanager
            jmesPath:
              - path: u
                objectAlias: MW_DB_USERNAME
              - path: p
                objectAlias: MW_DB_PASSWORD
    secretObjects:
    - secretName: {{ .Values.secretsStore.mwSecretAlias }}
      type: Opaque
      data:
        - objectName: MW_DB_PASSWORD
          key: MW_DB_PASSWORD
        - objectName: MW_DB_USERNAME
          key: MW_DB_USERNAME
{{ end }}