{{ if .Values.secretsStore.boxSecretEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "chart.fullname" . }}-secret-provider-class-box
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    app: {{ include "chart.fullname" . }}-secret-provider-class-box
    io.kompose.service: {{ include "chart.fullname" . }}-secret-provider-class-box
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secretsStore.secretRegion }}
    objects: |
      - objectName: {{ required "BoxCredsSecretName is required" .Values.secretsStore.BoxCredsSecretName }}
        objectType: secretsmanager
        jmesPath:
          - path: boxApiKey
            objectAlias: BOX_API_KEY
          - path: boxEncryptionKey
            objectAlias: BOX_ENCRYPTION_KEY
          - path: dbUsername
            objectAlias: DB_USERNAME
          - path: dbPassword
            objectAlias: DB_PASSWORD
  secretObjects:
  - secretName: {{ .Values.secretsStore.boxSecretAlias }}
    type: Opaque
    data:
      - objectName: BOX_API_KEY
        key: BOX_API_KEY
      - objectName: BOX_ENCRYPTION_KEY
        key: BOX_ENCRYPTION_KEY
      - objectName: DB_USERNAME
        key: DB_USERNAME
      - objectName: DB_PASSWORD
        key: DB_PASSWORD
{{ end }}
