apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}-worker-hpa
  namespace: {{ .Values.kubernetesNamespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}-worker
  minReplicas: {{ .Values.multiwovenWorker.hpa.minReplicas }}
  maxReplicas: {{ .Values.multiwovenWorker.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.multiwovenWorker.hpa.cpuAverageUtilizationPercentageThreshold }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.multiwovenWorker.hpa.memoryAverageUtilizationPercentageThreshold }}
