apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-server-{{ .Values.multiwovenConfig.appEnv }}
  namespace: {{ .Values.kubernetesNamespace }}-{{ .Values.multiwovenConfig.appEnv }}

  labels:
    io.kompose.service:  {{ include "chart.fullname" . }}-server-{{ .Values.multiwovenConfig.appEnv }}
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
spec:
  type: {{ .Values.multiwovenServer.type }}
  selector:
    io.kompose.service:  {{ include "chart.fullname" . }}-server-{{ .Values.multiwovenConfig.appEnv }}
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.multiwovenServer.ports | toYaml | nindent 2 -}}