{{ if .Values.secretsStore.lightningSecretEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "chart.fullname" . }}-secret-provider-class-lightning
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    app: {{ include "chart.fullname" . }}-secret-provider-class-lightning
    io.kompose.service: {{ include "chart.fullname" . }}-secret-provider-class-lightning
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ required "LightningCredsSecretName is required" .Values.secretsStore.LightningCredsSecretName }}
        objectType: secretsmanager
        jmesPath:
          - path: babelApiKey
            objectAlias: BABEL_API_KEY
          - path: polyApiKey
            objectAlias: POLY_API_KEY
          - path: chatApiKey
            objectAlias: CHAT_API_KEY
          - path: embeddingApiKey
            objectAlias: EMBEDDING_API_KEY
          - path: judyApiKey
            objectAlias: JUDY_API_KEY
          - path: multimodalChatApiKey
            objectAlias: MULTIMODAL_CHAT_API_KEY
          - path: pathfinderApiKey
            objectAlias: PATHFINDER_API_KEY
          - path: seemoreApiKey
            objectAlias: SEEMORE_API_KEY
          - path: sentinelApiKey
            objectAlias: SENTINEL_API_KEY
          - path: structuredExtractionApiKey
            objectAlias: STRUCTURED_EXTRACTION_API_KEY
          - path: xpertApiKey
            objectAlias: XPERT_API_KEY
  secretObjects:
  - secretName: {{ .Values.secretsStore.lightningSecretAlias }}
    type: Opaque
    data:
      - objectName: BABEL_API_KEY
        key: BABEL_API_KEY
      - objectName: POLY_API_KEY
        key: POLY_API_KEY
      - objectName: CHAT_API_KEY
        key: CHAT_API_KEY
      - objectName: EMBEDDING_API_KEY
        key: EMBEDDING_API_KEY
      - objectName: JUDY_API_KEY
        key: JUDY_API_KEY
      - objectName: MULTIMODAL_CHAT_API_KEY
        key: MULTIMODAL_CHAT_API_KEY
      - objectName: PATHFINDER_API_KEY
        key: PATHFINDER_API_KEY
      - objectName: SEEMORE_API_KEY
        key: SEEMORE_API_KEY
      - objectName: SENTINEL_API_KEY
        key: SENTINEL_API_KEY
      - objectName: STRUCTURED_EXTRACTION_API_KEY
        key: STRUCTURED_EXTRACTION_API_KEY
      - objectName: XPERT_API_KEY
        key: XPERT_API_KEY
{{ end }}
