apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-server
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    app: {{ include "chart.fullname" . }}-server
    io.kompose.service: {{ include "chart.fullname" . }}-server
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.multiwovenServer.replicas }}
  selector:
    matchLabels:
      app: {{ include "chart.fullname" . }}-server
      io.kompose.service: {{ include "chart.fullname" . }}-server
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "chart.fullname" . }}-server
        io.kompose.service: {{ include "chart.fullname" . }}-server
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "chart.fullname" . }}-config-{{ .Values.multiwovenConfig.appEnv }}
        image: {{ .Values.multiwovenServer.multiwovenServer.image.repository }}:{{ .Values.multiwovenServer.multiwovenServer.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ (index .Values.multiwovenServer.ports 0).port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        name: {{ include "chart.fullname" . }}-server
        ports:
        - containerPort: {{ (index .Values.multiwovenServer.ports 0).port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ (index .Values.multiwovenServer.ports 0).port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.multiwovenServer.multiwovenServer.resources | nindent 10 }}
{{ if not .Values.temporal.enabled }}
        imagePullPolicy: Always
        volumeMounts:
        - name: ssl
          mountPath: /certs
          readOnly: false
      volumes:
      - name: ssl
        secret:
          secretName: temporal-cloud
          items:
          - key: temporal-client-key
            path: ./temporal.key
          - key: temporal-root-cert
            path: ./temporal.pem
{{ end }}
      restartPolicy: Always
      {{ if .Values.multiwovenConfig.privateRepo }}
      imagePullSecrets:
        - name: {{ .Values.multiwovenConfig.registrySecretName }}
      {{ end }}