apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.externalDNS.enabled }}
      {{- if .Values.temporal.enabled }}
        external-dns.alpha.kubernetes.io/hostname: "{{ .Values.multiwovenConfig.uiHost }},{{ .Values.multiwovenConfig.apiHost }},{{ .Values.multiwovenConfig.workerHost }},{{ .Values.multiwovenConfig.temporalUiHost }}"
      {{- end }}
      {{- if not .Values.temporal.enabled }}
        external-dns.alpha.kubernetes.io/hostname: "{{ .Values.multiwovenConfig.uiHost }},{{ .Values.multiwovenConfig.apiHost }},{{ .Values.multiwovenConfig.workerHost }}"
      {{- end }}
    {{ end }}
    
    {{ if .Values.kongHqIngress.enabled }}
      {{- if .Values.kongHqIngress.plugins.prometheus.enabled }}
        konghq.com/plugins: 'prometheus-metrics'
      {{- end }}
    {{ end }}
    
    {{ if .Values.nginxIngress.enabled }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: {{ .Values.multiwovenConfig.tlsCertIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.multiwovenConfig.allowedSourceIP }}
    {{ end }}
    
spec:
  {{ if .Values.nginxIngress.enabled }}
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.multiwovenConfig.uiHost }}
    - {{ .Values.multiwovenConfig.apiHost }}
    - {{ .Values.multiwovenConfig.workerHost }}
  {{ if .Values.temporal.enabled }}
    - {{ .Values.multiwovenConfig.temporalUiHost }}
  {{ end }}
    secretName: mw-tls-cert
  {{ end }}
  
  {{ if .Values.kongHqIngress.enabled }}
    ingressClassName: kong
  {{ end }}
  rules:
  - host:  {{ .Values.multiwovenConfig.uiHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-ui'
            port:
              number: {{ (index .Values.multiwovenUI.ports 0).port }}
  - host: {{ .Values.multiwovenConfig.apiHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-server'
            port:
              number: {{ (index .Values.multiwovenServer.ports 0).port }}
  - host: {{ .Values.multiwovenConfig.workerHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-worker'
            port:
              number: {{ .Values.multiwovenWorker.healthPort }}
{{ if .Values.temporal.enabled }}
  - host: {{ .Values.multiwovenConfig.temporalUiHost }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-temporal-ui'
            port:
              number: {{ (index .Values.temporalUi.ports 0).port }}
        path: /
        pathType: Prefix
{{ end }}
