apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kubernetesNamespace }}-{{ .Values.multiwovenConfig.appEnv }}
  labels:
    name: {{ .Values.kubernetesNamespace }}-{{ .Values.multiwovenConfig.appEnv }}