apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-worker
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    service:  {{ include "chart.fullname" . }}-worker
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.multiwovenWorker.type }}
  selector:
    service:  {{ include "chart.fullname" . }}-worker
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.multiwovenWorker.ports | toYaml | nindent 2 -}}