apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-server
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    service:  {{ include "chart.fullname" . }}-server
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.multiwovenServer.type }}
  selector:
    service:  {{ include "chart.fullname" . }}-server
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.multiwovenServer.ports | toYaml | nindent 2 -}}