{{ if .Values.secretsStore.temporalSecretEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: {{ include "chart.fullname" . }}-secret-provider-class-temporal
    namespace: {{ .Values.kubernetesNamespace }}
    labels:
      app: {{ include "chart.fullname" . }}-secret-provider-class-temporal
      io.kompose.service: {{ include "chart.fullname" . }}-secret-provider-class-temporal
      {{- include "chart.labels" . | nindent 4 }}
spec:
    provider: aws
    parameters:
        region: {{ .Values.secretsStore.secretRegion | quote}}
        objects: |
          - objectName: {{ required "TemporalCredsSecretName is required" .Values.secretsStore.TemporalCredsSecretName }}
            objectType: secretsmanager
            jmesPath:
              - path: u
                objectAlias: TP_DB_USERNAME
              - path: p
                objectAlias: TP_DB_PASSWORD
    secretObjects:
    - secretName: {{ .Values.secretsStore.temporalSecretAlias }}
      type: Opaque
      data:
        - objectName: TP_DB_PASSWORD
          key: TP_DB_PASSWORD
        - objectName: TP_DB_USERNAME
          key: TP_DB_USERNAME
{{ end }}