apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  namespace: {{ .Values.kubernetesNamespace }}

  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: {{ .Values.multiwovenConfig.tlsCertIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.multiwovenConfig.allowedSourceIP }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.multiwovenConfig.uiHost }}
    - {{ .Values.multiwovenConfig.apiHost }}
  {{ if .Values.temporal.enabled }}
    - {{ .Values.multiwovenConfig.temporalUiHost }}
  {{ end }}
    secretName: mw-tls-cert
  rules:
  - host:  {{ .Values.multiwovenConfig.uiHost }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-ui'
            port:
              number: {{ (index .Values.multiwovenUI.ports 0).port }}
  - host: {{ .Values.multiwovenConfig.apiHost }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-server'
            port:
              number: {{ (index .Values.multiwovenServer.ports 0).port }}
  - host: {{ .Values.multiwovenConfig.workerHost }}
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-server'
            port:
              number: {{ .Values.multiwovenWorker.healthPort }}
{{ if .Values.temporal.enabled }}
  - host: {{ .Values.multiwovenConfig.temporalUiHost }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-temporal-ui'
            port:
              number: {{ (index .Values.temporalUi.ports 0).port }}
        path: /(.*)
        pathType: Prefix
{{ end }}
