{{ if .Values.secretsStore.appSecretEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "chart.fullname" . }}-secret-provider-class-app
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    app: {{ include "chart.fullname" . }}-secret-provider-class-app
    io.kompose.service: {{ include "chart.fullname" . }}-secret-provider-class-app
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secretsStore.secretRegion }}
    objects: |
      - objectName: {{ required "AppCredsSecretName is required" .Values.secretsStore.AppCredsSecretName }}
        objectType: secretsmanager
        jmesPath:
          - path: awsAccessKeyId
            objectAlias: AWS_ACCESS_KEY_ID
          - path: awsSecretAccessKey
            objectAlias: AWS_SECRET_ACCESS_KEY
          - path: appsignalPushApiKey
            objectAlias: APPSIGNAL_PUSH_API_KEY
          - path: boxApiKey
            objectAlias: BOX_API_KEY
          - path: codeExecSigningSecret
            objectAlias: CODE_EXEC_SIGNING_SECRET
          - path: hostedVectorDbUsername
            objectAlias: HOSTED_VECTOR_DB_USERNAME
          - path: hostedVectorDbPassword
            objectAlias: HOSTED_VECTOR_DB_PASSWORD
          - path: hubspotApiKey
            objectAlias: HUBSPOT_API_KEY
          - path: jwtSecret
            objectAlias: JWT_SECRET
          - path: maxmindLicenseKey
            objectAlias: MAXMIND_LICENSE_KEY
          - path: neonApiKey
            objectAlias: NEON_API_KEY
          - path: openrouterApiKey
            objectAlias: OPENROUTER_API_KEY
          - path: p2wLlmApiKey
            objectAlias: P2W_LLM_API_KEY
          - path: prometheusMetricsUsername
            objectAlias: PROMETHEUS_METRICS_USERNAME
          - path: prometheusMetricsPassword
            objectAlias: PROMETHEUS_METRICS_PASSWORD
          - path: promptToWorkflowApiKey
            objectAlias: PROMPT_TO_WORKFLOW_API_KEY
          - path: secretKeyBase
            objectAlias: SECRET_KEY_BASE
          - path: smtpUsername
            objectAlias: SMTP_USERNAME
          - path: smtpPassword
            objectAlias: SMTP_PASSWORD
          - path: storageAccessKey
            objectAlias: STORAGE_ACCESS_KEY
          - path: textractAccessKeyId
            objectAlias: TEXTRACT_ACCESS_KEY_ID
          - path: textractSecretAccessKey
            objectAlias: TEXTRACT_SECRET_ACCESS_KEY
  secretObjects:
  - secretName: {{ .Values.secretsStore.appSecretAlias }}
    type: Opaque
    data:
      - objectName: AWS_ACCESS_KEY_ID
        key: AWS_ACCESS_KEY_ID
      - objectName: AWS_SECRET_ACCESS_KEY
        key: AWS_SECRET_ACCESS_KEY
      - objectName: APPSIGNAL_PUSH_API_KEY
        key: APPSIGNAL_PUSH_API_KEY
      - objectName: BOX_API_KEY
        key: BOX_API_KEY
      - objectName: CODE_EXEC_SIGNING_SECRET
        key: CODE_EXEC_SIGNING_SECRET
      - objectName: HOSTED_VECTOR_DB_USERNAME
        key: HOSTED_VECTOR_DB_USERNAME
      - objectName: HOSTED_VECTOR_DB_PASSWORD
        key: HOSTED_VECTOR_DB_PASSWORD
      - objectName: HUBSPOT_API_KEY
        key: HUBSPOT_API_KEY
      - objectName: JWT_SECRET
        key: JWT_SECRET
      - objectName: MAXMIND_LICENSE_KEY
        key: MAXMIND_LICENSE_KEY
      - objectName: NEON_API_KEY
        key: NEON_API_KEY
      - objectName: OPENROUTER_API_KEY
        key: OPENROUTER_API_KEY
      - objectName: P2W_LLM_API_KEY
        key: P2W_LLM_API_KEY
      - objectName: PROMETHEUS_METRICS_USERNAME
        key: PROMETHEUS_METRICS_USERNAME
      - objectName: PROMETHEUS_METRICS_PASSWORD
        key: PROMETHEUS_METRICS_PASSWORD
      - objectName: PROMPT_TO_WORKFLOW_API_KEY
        key: PROMPT_TO_WORKFLOW_API_KEY
      - objectName: SECRET_KEY_BASE
        key: SECRET_KEY_BASE
      - objectName: SMTP_USERNAME
        key: SMTP_USERNAME
      - objectName: SMTP_PASSWORD
        key: SMTP_PASSWORD
      - objectName: STORAGE_ACCESS_KEY
        key: STORAGE_ACCESS_KEY
      - objectName: TEXTRACT_ACCESS_KEY_ID
        key: TEXTRACT_ACCESS_KEY_ID
      - objectName: TEXTRACT_SECRET_ACCESS_KEY
        key: TEXTRACT_SECRET_ACCESS_KEY
{{ end }}
