{{ if .Values.temporal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-temporal-ui
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    io.kompose.service: temporal-ui
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
spec:
  replicas: {{ .Values.temporalUi.replicas }}
  selector:
    matchLabels:
      io.kompose.service: temporal-ui
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/multiwoven-server-default: "true"
        io.kompose.service: temporal-ui
      {{- include "chart.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.temporalUi.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: {{ .Values.temporalUi.podSecurityContext.fsGroup }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken.enabled }}
      initContainers:
      {{ if .Values.securityContext.readOnlyRootFilesystem }}
      - name: copy-config
        image: {{ .Values.temporalUi.temporalUi.initContainer.image.repository }}:{{ .Values.temporalUi.temporalUi.initContainer.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.globalImagePullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            mkdir -p /mnt/home/ui-server
            echo "Copying /home/ui-server to /mnt/home/ui-server"
            cp -r /home/ui-server/* /mnt/home/ui-server/ || echo "/homes/ui-server directory is empty or missing"
        volumeMounts:
          - name: temporal-config
            mountPath: /mnt/home/ui-server
        securityContext:
          runAsUser: {{ .Values.temporalUi.temporalUi.containerSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.temporalUi.temporalUi.containerSecurityContext.runAsGroup }}
          privileged: false
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          capabilities:
            drop:
            {{- if .Values.securityContext.capabilities.drop.permissions }}
            {{- range .Values.securityContext.capabilities.drop.permissions }}
              - {{ . }}
            {{- end }}
            {{- end }}
      {{ end }}
      containers:
      - env:
        - name: TEMPORAL_ADDRESS
          value: {{ quote .Values.temporalUi.temporalUi.env.temporalAddress }}
        - name: TEMPORAL_CORS_ORIGINS
          value: {{ quote .Values.temporalUi.temporalUi.env.temporalCorsOrigins }}
        - name: TEMPORAL_UI_PORT
          value: {{ quote .Values.temporalUi.temporalUi.env.temporalUiPort }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.temporalUi.temporalUi.image.repository }}:{{ .Values.temporalUi.temporalUi.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.globalImagePullPolicy }}
        securityContext:
          runAsUser: {{ .Values.temporalUi.temporalUi.containerSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.temporalUi.temporalUi.containerSecurityContext.runAsGroup }}
          privileged: false
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          capabilities:
            drop:
            {{- if .Values.securityContext.capabilities.drop.permissions }}
            {{- range .Values.securityContext.capabilities.drop.permissions }}
              - {{ . }}
            {{- end }}
            {{- end }}
        name: temporal-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {{- toYaml .Values.temporalUi.temporalUi.resources | nindent 10 }}
        volumeMounts:
          {{ if .Values.securityContext.readOnlyRootFilesystem }}
          - name: temporal-config
            mountPath: /home/ui-server/
          {{ end }}
      volumes:
        {{ if .Values.securityContext.readOnlyRootFilesystem }}
        - name: temporal-config
          emptyDir: {}
        {{ end }}
      restartPolicy: Always
       {{ if .Values.multiwovenConfig.privateRepo }}
      imagePullSecrets:
        - name: {{ .Values.multiwovenConfig.registrySecretName }}
      {{ end }}
{{ end }}
