{{ if .Values.aisquaredPostgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-postgresql
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    io.kompose.service: {{ include "chart.fullname" . }}-postgresql
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aisquaredPostgresql.type }}
  selector:
    io.kompose.service: {{ include "chart.fullname" . }}-postgresql
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.aisquaredPostgresql.ports | toYaml | nindent 2 -}}
{{ end }}