{{ if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: {{ include "chart.fullname" . }}-secret-provider-class-ais
    namespace: {{ .Values.kubernetesNamespace }}
    labels:
      app: {{ include "chart.fullname" . }}-secret-provider-class-ais
      io.kompose.service: {{ include "chart.fullname" . }}-secret-provider-class-ais
      {{- include "chart.labels" . | nindent 4 }}
spec:
    provider: aws
    parameters:
        objects: |
          - objectName: {{ required "AISCredsSecretName is required" .Values.secretsStore.AISCredsSecretName }}
            objectType: secretsmanager
            jmesPath:
              - path: u
                objectAlias: AIS_DB_USERNAME
              - path: p
                objectAlias: AIS_DB_PASSWORD
    secretObjects:
    - secretName: {{ .Values.secretsStore.aisCredsSecretAlias }}
      type: Opaque
      data:
        - objectName: AIS_DB_PASSWORD
          key: AIS_DB_PASSWORD
        - objectName: AIS_DB_USERNAME
          key: AIS_DB_USERNAME
{{ end }}