apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.externalDNS.enabled }}
      {{- if .Values.temporal.enabled }}
        external-dns.alpha.kubernetes.io/hostname: "{{ .Values.aisquaredConfig.uiHost }},{{ .Values.aisquaredConfig.apiHost }},{{ .Values.aisquaredConfig.workerHost }},{{ .Values.aisquaredConfig.solidWorkerHost }},{{ .Values.aisquaredConfig.temporalUiHost }}"
      {{- end }}
      {{- if not .Values.temporal.enabled }}
        external-dns.alpha.kubernetes.io/hostname: "{{ .Values.aisquaredConfig.uiHost }},{{ .Values.aisquaredConfig.apiHost }},{{ .Values.aisquaredConfig.workerHost }},{{ .Values.aisquaredConfig.solidWorkerHost }}"
      {{- end }}
    {{ end }}
    
    {{ if .Values.kongIngress.enabled }}
      {{- if .Values.kongIngress.plugins.prometheus.enabled }}
        konghq.com/plugins: 'prometheus-metrics'
      {{- end }}
    {{ end }}
    
    {{ if .Values.nginxIngress.enabled }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: {{ .Values.aisquaredConfig.tlsCertIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.aisquaredConfig.allowedSourceIP }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.aisquaredConfig.nginxProxyBodySize }}
    {{ if .Values.nginxIngress.enableMetrics }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /metrics {
        return 403;
      } 
    {{ end }}
    {{ end }}
    
    {{ if .Values.awsIngress.enabled }}
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.awsIngress.acmCertificateArn }}"
    alb.ingress.kubernetes.io/scheme: {{ .Values.awsIngress.albScheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: {{ .Values.awsIngress.sslPolicy }}
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{ end }}

spec:
  {{ if .Values.nginxIngress.enabled }}
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.aisquaredConfig.uiHost }}
    - {{ .Values.aisquaredConfig.apiHost }}
    - {{ .Values.aisquaredConfig.workerHost }}
    - {{ .Values.aisquaredConfig.solidWorkerHost }}
  {{ if .Values.temporal.enabled }}
    - {{ .Values.aisquaredConfig.temporalUiHost }}
  {{ end }}
    secretName: mw-tls-cert
  {{ end }}
  
  {{ if .Values.kongIngress.enabled }}
  ingressClassName: kong
  {{ end }}
  {{ if .Values.awsIngress.enabled }}
  ingressClassName: alb
  {{ end }}
  rules:
  - host:  {{ .Values.aisquaredConfig.uiHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-ui'
            port:
              number: {{ (index .Values.aisquaredUI.ports 0).port }}
  - host: {{ .Values.aisquaredConfig.apiHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-server'
            port:
              number: {{ (index .Values.aisquaredServer.ports 0).port }}
  - host: {{ .Values.aisquaredConfig.workerHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-worker'
            port:
              number: {{ .Values.aisquaredWorker.healthPort }}
  - host: {{ .Values.aisquaredConfig.solidWorkerHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-solid-worker'
            port:
              number: {{ .Values.aisquaredSolidWorker.healthPort }}
{{ if .Values.temporal.enabled }}
  - host: {{ .Values.aisquaredConfig.temporalUiHost }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-temporal-ui'
            port:
              number: {{ (index .Values.temporalUi.ports 0).port }}
        path: /
        pathType: Prefix
{{ end }}
