name: Deploy to Staging

on:
  pull_request:
    branches: [ main ]
    types:
      - labeled

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy-to-staging' || contains( github.event.pull_request.labels.*.name, 'deploy-to-staging') }}
    environment: staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'
        id: install

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.1.3'

      - name: Gets K8s context
        uses: azure/aks-set-context@v3
        with:
            resource-group: ${{ vars.RESOURCE_GROUP }}
            cluster-name: ${{ vars.CLUSTER_NAME }}
            admin: 'false'
            use-kubelogin: 'true'

      - name: Deploy chart to staging
        run: |
          helm upgrade -i --reuse-values multiwoven ./charts/multiwoven /
            --set hpa.enabled=true /
            --set hpa.multiwovenUI.minReplicas=1 /
            --set hpa.multiwovenUI.maxReplicas=10 /
            --set hpa.multiwovenUI.cpuAverageUtilizationPercentageThreshold=80 /
            --set hpa.multiwovenUI.memoryAverageUtilizationPercentageThreshold=75 /
            --set hpa.multiwovenUI.behavior.scaleDown.stabilizationWindowSeconds=300 /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.percentPolicy.type=Percent /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.percentPolicy.value=100 /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.percentPolicy.periodSeconds=15 /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.podPolicy.type=Percent /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.podPolicy.value=100 /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.podPolicy.periodSeconds=15 /
            --set hpa.multiwovenUI.behavior.scaleDown.policies.selectPolicy=Max /
            --set hpa.multiwovenUI.behavior.scaleUp.stabilizationWindowSeconds=300 /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.percentPolicy.type=Percent /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.percentPolicy.value=100 /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.percentPolicy.periodSeconds=15 /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.podPolicy.type=Pods /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.podPolicy.value=4 /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.podPolicy.periodSeconds=15 /
            --set hpa.multiwovenUI.behavior.scaleUp.policies.selectPolicy=Max /
            --set hpa.multiwovenServer.minReplicas=1 /
            --set hpa.multiwovenServer.maxReplicas=10 /
            --set hpa.multiwovenServer.cpuAverageUtilizationPercentageThreshold=80 /
            --set hpa.multiwovenServer.memoryAverageUtilizationPercentageThreshold=60 /
            --set hpa.multiwovenServer.behavior.scaleDown.stabilizationWindowSeconds=300 /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.percentPolicy.type=Percent /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.percentPolicy.value=100 /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.percentPolicy.periodSeconds=15 /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.podPolicy.type=Percent /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.podPolicy.value=100 /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.podPolicy.periodSeconds=15 /
            --set hpa.multiwovenServer.behavior.scaleDown.policies.selectPolicy=Max /
            --set hpa.multiwovenServer.behavior.scaleUp.stabilizationWindowSeconds=300 /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.percentPolicy.type=Percent /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.percentPolicy.value=100 /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.percentPolicy.periodSeconds=15 /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.podPolicy.type=Pods /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.podPolicy.value=4 /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.podPolicy.periodSeconds=15 /
            --set hpa.multiwovenServer.behavior.scaleUp.policies.selectPolicy=Max /
            --set hpa.multiwovenWorker.minReplicas=1 /
            --set hpa.multiwovenWorker.maxReplicas=10 /
            --set hpa.multiwovenWorker.cpuAverageUtilizationPercentageThreshold=80 /
            --set hpa.multiwovenWorker.memoryAverageUtilizationPercentageThreshold=50 /
            --set hpa.multiwovenWorker.behavior.scaleDown.stabilizationWindowSeconds=300 /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.percentPolicy.type=Percent /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.percentPolicy.value=100 /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.percentPolicy.periodSeconds=15 /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.podPolicy.type=Percent /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.podPolicy.value=100 /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.podPolicy.periodSeconds=15 /
            --set hpa.multiwovenWorker.behavior.scaleDown.policies.selectPolicy=Max /
            --set hpa.multiwovenWorker.behavior.scaleUp.stabilizationWindowSeconds=300 /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.percentPolicy.type=Percent /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.percentPolicy.value=100 /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.percentPolicy.periodSeconds=15 /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.podPolicy.type=Pods /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.podPolicy.value=4 /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.podPolicy.periodSeconds=15 /
            --set hpa.multiwovenWorker.behavior.scaleUp.policies.selectPolicy=Max
          kubectl rollout restart deployment ${{ vars.APP_ENV }}-multiwoven-worker -n multiwoven
          kubectl rollout restart deployment ${{ vars.APP_ENV }}-multiwoven-server -n multiwoven
          kubectl rollout restart deployment ${{ vars.APP_ENV }}-multiwoven-ui -n multiwoven