name: Version Check

on:
  pull_request:
    branches: [ main ]
  
jobs:
  version-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Get latest version
        id: latestVersion
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: helm show chart multiwoven --repo https://multiwoven.github.io/helm-charts | yq '.version'

      - name: Compare versions
        run: \
          echo ${{ steps.lookupSdkVersion.outputs.result }}