name: Version Check

on:
  pull_request:
    branches: [ main ]
  
jobs:
  version-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'
        id: install

      - name: Set env
        run: echo "CHART_INFO=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Get latest version
        id: latestVersion
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: echo $CHART_INFO | yq '.version'

      - name: Compare versions
        run: |
          echo ${{ steps.latestVersion.outputs.result }}