name: Version Check

on:
  pull_request:
    branches: [ main ]
  
jobs:
  version-check:
    runs-on: ubuntu-22.04
    steps:
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: /
            LATEST=$(helm show chart multiwoven --repo https://multiwoven.github.io/helm-charts | yq '.version')
            echo "Latest version:\n$LATEST\n"
            CURRENT=$(yq '.version' charts/multiwoven/Chart.yaml)
            APP_VERSION=$(yq '.appVersion' charts/multiwoven/Chart.yaml)
            echo "Current version:\nversion $CURRENT\nappVersion $APPVERSION"
            if [ $LATEST = $CURRENT ] || [ $LATEST = $APP_VERSION ]; then
                echo "Chart version has not been updated!"
                exit 1
            fi